name: meme_maker
description: Meme makes easy
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  awesome_flutter_extensions: ^1.2.0
  bloc: ^8.1.4
  dartx: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.3
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  no_screenshot: ^0.2.0
  octo_image: ^2.1.0
  uuid: ^4.4.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
